export const rows = [
  {
    id: 1,
    combination: 'ones',
    displayName: 'Ones',
    points: 'Total of all 1s',
    playerOne: 0,
    playerTwo: 0,
  },
  {
    id: 2,
    combination: 'twos',
    displayName: 'Twos',
    points: 'Total of all 2s',
    playerOne: 0,
    playerTwo: 0,
  },
  {
    id: 3,
    combination: 'threes',
    displayName: 'Threes',
    points: 'Total of all 3s',
    playerOne: 0,
    playerTwo: 0,
  },
  {
    id: 4,
    combination: 'fours',
    displayName: 'Fours',
    points: 'Total of all 4s',
    playerOne: 0,
    playerTwo: 0,
  },
  {
    id: 5,
    combination: 'fives',
    displayName: 'Fives',
    points: 'Total of all 5s',
    playerOne: 0,
    playerTwo: 0,
  },
  {
    id: 6,
    combination: 'sixes',
    displayName: 'Sixes',
    points: 'Total of all 6s',
    playerOne: 0,
    playerTwo: 0,
  },
  {
    id: 7,
    combination: 'bonus',
    displayName: 'Bonus (if total above is min 63)',
    points: '35',
    playerOne: 0,
    playerTwo: 0,
  },
  {
    id: 8,
    combination: 'pair',
    displayName: 'Pair',
    points: 'Sum of highest pair',
    playerOne: 0,
    playerTwo: 0,
  },
  {
    id: 9,
    combination: 'twoPairs',
    displayName: 'Two Pairs',
    points: 'Sum of 2 pairs',
    playerOne: 0,
    playerTwo: 0,
  },
  {
    id: 10,
    combination: 'threeOfKind',
    displayName: '3 of a kind',
    points: 'Sum of 3 of a kind',
    playerOne: 0,
    playerTwo: 0,
  },
  {
    id: 11,
    combination: 'fourOfKind',
    displayName: '4 of a kind',
    points: 'Sum of 4 of a kind',
    playerOne: 0,
    playerTwo: 0,
  },
  {
    id: 12,
    combination: 'fullHouse',
    displayName: 'Full House',
    points: '25',
    playerOne: 0,
    playerTwo: 0,
  },
  {
    id: 13,
    combination: 'smStraight',
    displayName: 'Small Straight (sequence of 4)',
    points: '30',
    playerOne: 0,
    playerTwo: 0,
  },
  {
    id: 14,
    combination: 'lgStraight',
    displayName: 'Large Straight (sequence of 5)',
    points: '40',
    playerOne: 0,
    playerTwo: 0,
  },
  {
    id: 15,
    combination: 'chance',
    displayName: 'Chance',
    points: 'Sum of all dice',
    playerOne: 0,
    playerTwo: 0,
  },
  {
    id: 16,
    combination: 'yatzy',
    displayName: 'YATZY',
    points: '50',
    playerOne: 0,
    playerTwo: 0,
  },
];
